def get_node_env() {
    switch (BRANCH_NAME) {
        case 'master':
            return 'production'
        case 'develop':
            return 'development'
        default:
            return 'development'
    }
}
def automatedTests (){
    if (NODE_ENV == 'development') {
        echo 'Running dev tests'
        sh "docker exec $CONTAINER_NAME sh -c 'yarn test'"
    } else {
        echo 'Skipping dev tests'
    }
}

pipeline {
    agent any
    environment {
        DOCKERFILE_BASE = sh(script: 'cat devops/DockerfileBase', returnStdout: true)
        DOCKERHUB_CREDENTIALS = credentials('2255ea73-6c59-4ead-b350-a05ba2022fcc')
        REGISTRY = 'adpopescu3382/devops-playground'
        IMAGE_TAG = "node-app-${BRANCH_NAME}"
        CONTAINER_NAME = 'node-app'
        NODE_ENV = get_node_env()
    }

    stages {
        stage('Base image updated check') {
            steps {
                script {
                    echo 'Checking if base image needs to be updated'

                    if (currentBuild.previousBuild) {
                        echo 'Previous build found'
                        def lastDockerfileBase = currentBuild.previousBuild.buildVariables?.BASE_IMAGE
                        if (DOCKERFILE_BASE != lastDockerfileBase) {
                            echo 'DockerfileBase has changed, building new image'
                            // build new base image
                            sh "docker build -f devops/DockerfileBase -t $REGISTRY:$IMAGE_TAG-base ."
                            // docker login
                            sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                            // push image to registry
                            sh "docker push $REGISTRY:$IMAGE_TAG-base"
                            echo 'Image pushed to registry'
                        } else {
                            echo 'DockerfileBase has not changed, using existing image'
                        }
                    } else {
                        echo 'No previous build found, building new image'
                        // build new base image
                        sh "docker build -f devops/DockerfileBase -t $REGISTRY:$IMAGE_TAG-base ."
                        // docker login
                        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                        // push image to registry
                        sh "docker push $REGISTRY:$IMAGE_TAG-base"
                        echo 'Image pushed to registry'
                    }

                    // update env variable for next build
                    env.BASE_IMAGE = DOCKERFILE_BASE
                }
            }
        }

        stage('Build') {
            steps {
                echo "Building image $REGISTRY:$IMAGE_TAG for branch $BRANCH_NAME"
                // pass base image as build arg to Dockerfile
                sh "docker build -t $REGISTRY:$IMAGE_TAG . --build-arg BASE_IMAGE=$REGISTRY:$IMAGE_TAG-base --build-arg NODE_ENV=$NODE_ENV"
            }
        }

        stage('Test') {
            steps {
                echo 'Testing..'
                // start container
                sh "docker run -d --name $CONTAINER_NAME -p 3000 $REGISTRY:$IMAGE_TAG"
                // run automated tests
                automatedTests()
                // check that server is running
                // make a curl req to server and log response
                sh """
                    docker exec $CONTAINER_NAME sh -c 'curl -s http://localhost:3000/hello'
                    | tee /tmp/output.txt 
                    && cat /tmp/output.txt
                    | xargs -I {} echo "server response: {}"
                """
                echo "server is running fine"
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying....'
                // docker login
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                // push image to registry
                sh "docker push $REGISTRY:$IMAGE_TAG"
            }
        }
    }
    post { 
        always { 
            cleanWs()
            sh 'docker logout'
            // TODO: check that container is actually running before deleting it
            // stop and remove container
            sh "docker stop $CONTAINER_NAME"
            sh "docker rm $CONTAINER_NAME"
            // remove image
            sh "docker rmi $REGISTRY:$IMAGE_TAG"
        }
        // TODO:
        // on failure, send email
        // on success, send email
    }
}